config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :items, :actions

  devise_for :users
  get 'user_items/:user_id' => 'items#user', as: :user_items

  root 'home#index'

end

app/models/action.rb
# == Schema Information
#
# Table name: actions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  item_id    :integer
#  owner      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Action < ActiveRecord::Base
  belongs_to :user
  belongs_to :item


  validates :user_id, presence: true
  validates :item_id, presence: true
  validates :owner, presence: true
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer          not null, primary key
#  name         :string
#  description  :text
#  available    :boolean
#  start_avail  :date
#  finish_avail :date
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  image        :string
#

class Item < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
  has_one :user_detail
  has_many :actions
  def handle
    self.email.split('@') [0]
  end
end

app/models/user_detail.rb
# == Schema Information
#
# Table name: user_details
#
#  id          :integer          not null, primary key
#  username    :string
#  name_first  :string
#  name_last   :string
#  zipcode     :string
#  address_st  :string
#  address_hno :integer
#  address_cpm :string
#  city        :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class UserDetail < ActiveRecord::Base
  belongs_to :user

  validates :zipcode, presence: true
end

app/controllers/actions_1_controllers.rb
class ActionsController < ApplicationController

  def index
    @actions = Action.all
    #@actions = Action.where("user_id = ?", params[:current_user])
  end

  def show
  end

  def new
    @action = Action.new
    @action.item_id = params[:item_id]
  end


  def create
    @action = Action.new(action_params)
    @action.user_id = current_user
    @action.owner = item.user_id

    respond_to do |format|
      if @action.save
        format.html { redirect_to @action, notice: 'Item was succefully reserved.'}
      else
        format.html { render :new}
      end
    end
  end

  def edit
  end
  
  def update
    @action = Action.find params[:id]
    respond_to do |format|
      if @action.update(action_params)
        format.html { redirect_to @action, notice: "Item reservation was updated with success."}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @action.destroy
    respond_to do |format|
      format.html { redirect_to actions_url, notice: "Reservation was deleted."}
    end
  end

  private

  def set_action
    @action = Action.find(params[:id])
  end

  def action_params
    params.require(:action).permit(:user_id, :item_id, :owner)
  end
end

app/controllers/actions_controllers.rb
class ActionsController < ApplicationController

  def index
    @actions = Action.all
    #@actions = Action.where("user_id = ?", params[:current_user])
  end

  def show
  end

  def new
    @action = Action.new
    @action.item_id = params[:item_id]
  end


  def create
    @action = Action.new(action_params)
    @action.user_id = current_user
    @action.owner = item.user_id

    respond_to do |format|
      if @action.save
        format.html { redirect_to @action, notice: 'Item was succefully reserved.'}
      else
        format.html { render :new}
      end
    end
  end

  def edit
  end
  
  def update
    @action = Action.find params[:id]
    respond_to do |format|
      if @action.update(action_params)
        format.html { redirect_to @action, notice: "Item reservation was updated with success."}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @action.destroy
    respond_to do |format|
      format.html { redirect_to actions_url, notice: "Reservation was deleted."}
    end
  end

  private

  def set_action
    @action = Action.find(params[:id])
  end

  def action_params
    params.require(:action).permit(:user_id, :item_id, :owner)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def show

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_item, only: [:show, :update, :destroy]

  def index
    @items = Item.order(name: :asc)
    @available_items = Item.where(available: :true)
    @unavailable_items = Item.where(available: :false)
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find( params[:id] )
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    respond_to do |format|
      if @item.save
        format.html { redirect_to item: @item.id, notice: 'Item was succefully created.'}
        format.json { render status: :created}
      else
        format.html { redirect_to items_path, notice: 'Item was not created.'}
        format.json { render json: @item.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    @item = Item.find params[:id]
    respond_to do |format|
      if @item.update(item_params)
        format.html {redirect_to @item, notice: 'Item was updated.'}
      else
        format.html {render :edit }
      end
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: 'Item was removed with success.'
  end



  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:user_id, :name, :description, :image, :available, :start_avail, :finish_avail)
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  def index
    @user_detail = current_user
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def toggle_btn(available)
    case available
    when true
      'This item <i style="color:green" class="fa fa-toggle-on"></i>'
    when false
      'This item <i style="color:red" class="fa fa-toggle-off"></i>'
    end
  end
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/actions/index_1.html.erb
<%= render 'layouts/header' %>


<main class="container">
<h1> List Reservations of Items</h1>


    <% @actions.each do |action| %>
      <%= action.user_id %>
      <%= action.item_id %>
      <%= action.owner %>
    <% end %>

</main>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<!--<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">-->
</head>

<body>
<h1 ><i style="color:grey" class="fa fa-users"></i> Why Buy if you can lend it and borrow it? <i style="color:grey" class="fa fa-users"></i></h1>

<div>
  <p style="color:darkred" class="notice"><%= notice %></p>
  <p  class="alert" style="color:red"><%= alert %></p>
  <%= yield %>

  <ul>
    <h3 class="Available Items">Available Items</h3>
    <%= link_to('Items', items_path, class: "btn btn-primary")%>
    <%= link_to('Actions', actions_path, class: "btn btn-info")%>
  </ul>
  <br/>
</div>

<br/>
<div>
  <% if user_signed_in? %>
  <ul>
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-warning") %>
  </ul>
  <ul>
    <%= link_to('Edit Registration', edit_user_registration_path, class: "btn btn-info") %>
  </ul>
<% else %>
  <ul>
    <%= link_to('Login', new_user_session_path, class: "btn btn-primary")  %>
  </ul>
  <ul>
    <%= link_to('Register', new_user_registration_path, class: "btn btn-info")  %>
  </ul>
<% end %>
</div>
</body>

app/views/items/_avail_items_form.html.erb
<%= form_for (@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibed this <strong>item<strong> to be saved.</h2>

    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= f.hidden_field :user_id, value: current_user.id %>
<% @available_items.each do |item_a|%>
<div>
  <h4><%= link_to item_a.name, item_a %></h4>
</div>
<% end %>

<% end %>

app/views/items/_form.html.erb
  <%= form_for (@item) do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibed this <strong>item<strong> to be saved.</h2>

      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <br/>
    <div class="form-group">
      <%= f.label :description %><br/>
      <%= f.text_area :description, size: "48x6" %>
    </div>
    <div class="checkbox">
      <%= f.label :available %>
      <%= f.check_box :available %>

    </div>
    <!-- <div>
      <br/>
      <%= f.label :image %><br/>
      <%= f.file_field :image %> -->

    </div>
    <div class="date">
      <br/>
      <%= f.label "Available from" %>
      <%= f.date_field :start_avail %>
    </div>
    <div class="date">
      <%= f.label "Available until " %>
      <%= f.date_field :finish_avail %>

    </div>
    <br/>
    <div class="btn-group">
      <%= link_to 'Return', items_path, class: "btn btn-default"%>
      <%= f.submit (@item.new_record? ? "Create" : "Update"), class: "btn btn-primary"%>
    </div>
  </div>
  <% end %>

app/views/items/index.html.erb
<%= render 'layouts/header' %>


<main class="container">
  <div>
    <%= link_to 'Home', root_path, class: "btn btn-primary" %>
    <% if user_signed_in? %>
      <%= link_to 'New Item', new_item_path, class: "btn btn-primary" %>
      <br/>
    <% end %>
  </div>
  <br/>
<h1>Items - complete list</h1>

<% @items.each do |item| %>
  <div>
    <p><%= link_to item.name, item %></p>
    <h5><%= item.description %></h5>
  </div>
<% end %>

</main>

app/views/items/new.html.erb
<h2>Create New Item</h2>

<%= render 'form' %>

app/views/items/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<!-- <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet"> -->
</head>

<body>
  <%= render 'layouts/header' %>


  <main class="container">
    <h1>
      <%= @item.name.titleize %>
    </h1>

    <div>
      <% if @item.available? %>
        <h3 style="color:green">This item is available <i class="fa fa-toggle-on"></i></h3>
      <% else %>
        <h3 style="color:darkred">This item is not available <i class="fa fa-toggle-off"></i></h3>
    <% end %>
    </div>
    <p><%= @item.description %></p>
    <p>Owner: <%= @item.user.handle.capitalize %></p>
    <div>
    <!--<div>
      < image_tag (item.image.thumbnail_url, class:"thumbnail inline" >
    </div>-->
      <br/>
      <br/>
      <% if @item.user_id = current_user.id? %>
        <%= render 'form' %>
      <% else %>
        <p>are you interested?</p>
      <% end %>
    </div>
    </main>
</body>
</html>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
   <div class="container">
     <%= link_to "WhyBuy", '/', class: "navbar-brand" %>
     <nav>
       <div class="row">
         <ul class="nav navbar-nav">
           <li><%= link_to "Items", items_path %></li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
           <span class="navbar-text"><%= signed_in? ? current_user.email : ""%></span>
         </ul>
      </div>
     </nav>
   </div>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whybuy </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header"%>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container">
      <%= yield %>
    </main>
  </div>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhybuyRailsRspec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p> test </p>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/items.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whybuy Items List</title>

</head>
<body>

  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container">
      <%= yield %>
    </main>
  </div>

</body>
</html>

app/views/user_details/_user_details.html.erb
<h1> User Details </h1>

<h2> <%= current_user.email %> </h2>

app/views/user_details/index.html.erb
<h1><%= User Details "#{current_user.email}" %></h1>
<%= render @user_detail %>

app/views/user_details/show.html.erb
<h1>UserDetails#show</h1>
<p>Find me in app/views/user_details/show.html.erb</p>